# ================================================================
# WTS CMS
# Powered By Webskitters Technology Solutions Pvt. Ltd.
# Website: https://www.webskitters.com
# ================================================================
packages:
  - "apps/*"
  - "packages/*"

overrides:
  postcss: "8.5.14"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
